# hugo.toml

baseURL = "https://rahulg.space/"
languageCode = "en-us"
title = "Rahul Gupta"
theme = ["github.com/luizdepra/hugo-coder"]

[pagination]
  pagerSize = 10
enableRobotsTXT = true

[params]
  author = "Rahul Gupta"
  info = "Tech Enthusiast"
  description = "Rahul Gupta"
  avatarURL = "/images/avatar.jpg" # Optional: add an image to /static/images/
  since = 2025

# --- Dark Mode Settings ---
  colorscheme = "auto"
  hideColorSchemeToggle = false

# Disable taxonomies you don’t use (removes warnings about missing layouts)
disableKinds = ["taxonomy", "taxonomyTerm"]

# We only need the home page
[outputs]
  home = [ "HTML" ]
  page = [ "HTML" ]
  section = [ "HTML" ]